### ISSUE TITLE
¿Agregar glyphs del español?

### ISSUE THREAD

**Issue by CrisA-Works** [impallari/Libre-Clarendon#3]
Pablo! Siempre vuelvo de vez en cuando a esta tipografía, para volverme a acordar que no tiene acentos </3

¿Sería posible en algún momento agregárselos? Es la única razón por la que la tengo en el cajón. Dave Crossland [está buscando financiar proyectos de tipografías para Google Fonts 2023](https://typedrawers.com/discussion/4521/projects-google-fonts-ought-to-fund-in-2023#latest), quizá eso motive a trabajar en lo que pueda faltarle!

**Comment by impallari** [comment]
Hola Cris.
Gracias por hacerme el agante!
Con un poquito de suerte y viento a favor, este año la terminamos. Vamos a meterle huevos, a ver que pasa!

**Comment by impallari** [comment]
Ya estoy de nuevo a full Cristobal, la estoy mejorando mucho. Creo que antes de fin de año la termino :)

**Comment by CrisA-Works** [comment]
Buenísimoo! Admiro la dedicación! Conseguiste que Google financiara el proyecto?

**Comment by impallari** [comment]
Conseguí concetrarme un poco y ponerme a trabajar :)
